name: Docker Image CI

on:
    push:
     branches: [ "main" ]
    workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
       
    - name: Login to personal registry
      uses: docker/login-action@v2 
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: github.event_name != 'pull_request'

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
         context: .
         platforms: linux/amd64,linux/arm64
         push: true
         tags: qjoly/prezgit:latest
      if: github.event_name != 'pull_request'
      
    - name: Build only (PR)
      uses: docker/build-push-action@v3
      with:
         context: .
         platforms: linux/amd64
         push: false
         tags: qjoly/prezgit
      if: github.event_name == 'pull_request'   
       
    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        readme: ./README.md
        repository: "qjoly/prezgit"
      if: github.event_name != 'pull_request'

    - uses: rickstaa/action-create-tag@v1
      with:
         tag: ${{github.run_number}}
