name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: |
            mkdir build
            cp -R img build/

      - name: Marp Build (Html)
        uses: docker://marpteam/marp-cli:v1.7.2
        with:
          args: slide-deck.md -o build/index.html --html --bespoke.progress --template bespoke
        env:
          MARP_USER: root:root
          
      - name: Marp Build (pdf)
        uses: docker://marpteam/marp-cli:v1.7.2
        with:
          args: slide-deck.md -o build/Prezgit.pdf --pdf --bespoke.progress --template bespoke --allow-local-files
        env:
          MARP_USER: root:root

      - name: Marp Build (pptx)
        uses: docker://marpteam/marp-cli:v1.7.2
        with:
          args: slide-deck.md -o build/Prezgit.pptx --pptx --bespoke.progress --template bespoke --allow-local-files
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/

